#181 Improve documentation (#185)
* #181 Savepoint

* #181 Savepoint

* #181 Savepoint

* #181 Savepoint

* #181 Savepoint

* #181 Savepoint

* #181 Savepoint

* #181 Savepoint

* #181 Savepoint

* #181 Savepoint

* #181 Savepoint

* #181 Savepoint

* #181 Savepoint

* #181 Remove /usr/bin/env python3

* #181 Move code inside try-except block

* #181 Adjust variable names

* #181 Adjust variable names

* #181 modify from . import statements

* #181 Add datasources

* #181 Update errors

* #181 Add documentation examples

* #181 Wordsmithing

* #181 Fix action errors

* #181 Prepare for versioned release

* Force re-test

diff --git a/.github/workflows/pytest-linux.yaml b/.github/workflows/pytest-linux.yaml
--- a/.github/workflows/pytest-linux.yaml
+++ b/.github/workflows/pytest-linux.yaml
@@ -3,7 +3,9 @@ name: pytest linux
 on: [push, pull_request]
 
 env:
+  LD_LIBRARY_PATH: /opt/senzing/er/lib
   PYTHONPATH: /home/runner/work/sz-sdk-python/sz-sdk-python/src
+  SENZING_TOOLS_DATABASE_URL: sqlite3://na:na@nowhere/tmp/sqlite/G2C.db
 
 permissions:
   contents: read
@@ -17,6 +19,7 @@ jobs:
       matrix:
         os: [ubuntu-latest]
         python-version: ["3.9", "3.10", "3.11", "3.12"]
+        senzingsdk-version: [staging-v4]
 
     steps:
       - name: Checkout repository
@@ -34,6 +37,7 @@ jobs:
           echo "PATH=${PATH}" >> "${GITHUB_ENV}"
           python -m pip install --upgrade pip
           python -m pip install --requirement requirements.txt
+          python -m pip install --requirement test-requirements.txt
           python -m pip install psutil pytest pytest-cov pytest-schema
 
       - if: matrix.python-version == '3.8' || matrix.python-version == '3.9' || matrix.python-version == '3.10'
@@ -42,22 +46,57 @@ jobs:
           source ./venv/bin/activate
           python -m pip install typing_extensions
 
+      - name: Install Senzing SDK
+        uses: senzing-factory/github-action-install-senzing-sdk@v2
+        with:
+          senzingsdk-repository-package: ${{ secrets.SENZING_APT_BETA_STAGING_REPOSITORY_PACKAGE }}
+          senzingsdk-repository-path: ${{ secrets.SENZING_APT_BETA_STAGING_REPOSITORY_URL }}
+
+      - name: Copy /etc files
+        run: |
+          sudo mkdir -p /etc/opt/senzing
+          sudo cp testdata/senzing-license/g2.lic /etc/opt/senzing/g2.lic
+
+      - name: Copy test database files
+        run: |
+          mkdir /tmp/sqlite
+          cp testdata/sqlite/G2C.db /tmp/sqlite/G2C.db
+
       - name: Run pytest on tests
         run: |
           source ./venv/bin/activate
           pytest tests/ --verbose --capture=no --cov=src --cov-append
 
-      - name: Run unittest on examples
+      # Use pytest to check examples, there are no "test" classes/functions, pytest imports
+      # the .py files. If there is a Python error in the examples, an exit code of 1
+      # is returned. If there are no Python errors but pytest didn't think it found any
+      # tests an exit code of 5 is returned, this is a pass but need to capture it and
+      # return 0 - https://docs.pytest.org/en/stable/reference/exit-codes.html
+      - name: Run pytest on examples
         run: |
           source ./venv/bin/activate
-          python3 -m unittest \
-            examples/szconfig/*.py \
-            examples/szconfigmanager/*.py \
-            examples/szdiagnostic/*.py \
-            examples/szengine/*.py \
-            examples/szproduct/*.py \
-            examples/misc/*.py \
-            || true
+          set +e
+          pytest \
+            examples/misc/ \
+            examples/docs/ \
+            examples/extras/ \
+            examples/szabstractfactory/ \
+            examples/szconfig/ \
+            examples/szconfigmanager/ \
+            examples/szdiagnostic/ \
+            examples/szengine/ \
+            examples/szproduct/ \
+            --capture=no \
+            -o python_files=*.py \
+            --verbose
+          pytest_exit_code="$?"
+          set -e
+          if [ "$pytest_exit_code" -eq 5 ]; then
+            echo -e "\nExit code from pytest was $pytest_exit_code, this is expected testing the examples if there were no Python errors\n"
+            exit 0
+          else
+            exit "$pytest_exit_code"
+          fi
 
       - name: Rename coverage file
         env:
